// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-vec.cuh"

// NOTE: GGML_TYPE_F8_E5M2 is not yet defined in ggml.h
// These template instances are disabled until the type is added to the type system
// DECL_FATTN_VEC_CASE( 64, GGML_TYPE_F16, GGML_TYPE_F8_E5M2);
// DECL_FATTN_VEC_CASE(128, GGML_TYPE_F16, GGML_TYPE_F8_E5M2);
// DECL_FATTN_VEC_CASE(256, GGML_TYPE_F16, GGML_TYPE_F8_E5M2);
