/**
 * SECTION 7: Decode Loop Offload - Persistent Kernel Orchestration
 * Header: GPU-side persistent kernel API
 */

#pragma once

#include "llama.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// PERSISTENT KERNEL STATUS
// ============================================================================

struct llama_persistent_kernel_status {
    bool kernel_active;
    bool should_stop;
    int iteration_count;
    int max_iterations;
    int total_tokens;
    int cuda_errors;
    uint64_t elapsed_ns;
};

// ============================================================================
// LIFECYCLE API
// ============================================================================

/**
 * Initialize persistent kernel infrastructure.
 * Allocates GPU buffers for persistent execution.
 *
 * @param max_tokens Maximum tokens to generate in one session
 * @return 0 on success, -1 on error
 */
int llama_persistent_kernel_init(int max_tokens);

/**
 * Launch persistent kernel.
 * Kernel will run in a loop on GPU, generating tokens until stopped.
 * This call returns immediately (non-blocking).
 *
 * @param ctx Llama context
 * @param max_tokens Maximum tokens to generate
 * @return 0 on success, -1 on error
 */
int llama_persistent_kernel_launch(const llama_context * ctx, int max_tokens);

/**
 * Signal persistent kernel to stop.
 * Non-blocking - kernel finishes current iteration then exits.
 *
 * @return 0 on success
 */
int llama_persistent_kernel_stop();

/**
 * Wait for persistent kernel to complete.
 * Polls until kernel finishes or timeout.
 *
 * @param timeout_ms Maximum wait time in milliseconds
 * @return 0 if completed, -1 if timeout
 */
int llama_persistent_kernel_wait(int timeout_ms);

/**
 * Cleanup persistent kernel resources.
 */
int llama_persistent_kernel_cleanup();

// ============================================================================
// OUTPUT RETRIEVAL
// ============================================================================

/**
 * Get tokens generated by persistent kernel.
 * Copies output from GPU to CPU buffer.
 *
 * @param output Output buffer for tokens
 * @param max_count Maximum tokens to copy
 * @return Number of tokens copied
 */
int llama_persistent_kernel_get_tokens(int * output, int max_count);

// ============================================================================
// QUERY API
// ============================================================================

/**
 * Get current status of persistent kernel.
 */
struct llama_persistent_kernel_status llama_persistent_kernel_get_status();

// ============================================================================
// CONTROL
// ============================================================================

/**
 * Enable/disable persistent kernel execution.
 * Default: disabled (traditional per-token execution)
 */
void llama_persistent_kernel_set_enabled(bool enabled);

/**
 * Check if persistent kernel is enabled.
 */
bool llama_persistent_kernel_is_enabled();

/**
 * Print kernel statistics (for profiling/debugging).
 */
void llama_persistent_kernel_print_stats();

#ifdef __cplusplus
}
#endif
